### ISSUE TITLE
Question about wallpaper cropping.

### ISSUE THREAD

**Issue by gaabster** [Hamza417/Peristyle#59]
Hello.

When applying wallpaper manually, the app asks **Would I like to use cropped wallpaper as visible on screen** and the image fits perfectly. But when the same image is applied automatically it looks to be zoomed in much more.
Why is that?

<details>
  <summary>auto</summary>
 
![Screenshot_20240628-165855_Pie Launcher](https://github.com/Hamza417/Peristyle/assets/29731884/96289ec7-02ee-4167-9281-cae4d5fc4acf)

</details>

<details>
  <summary>manual</summary>

![Screenshot_20240629-102526_Pie Launcher](https://github.com/Hamza417/Peristyle/assets/29731884/6f41314c-aea7-47bb-bc98-ba18ebf05711)

</details>

There are more extreme cases.
Have a good day everyone.

**Comment by Hamza417** [comment]
The two works differently, when wallpaper is visible it's easier to crop the image since everything's laid out on the screen. The auto wallpaper doesn't know anything except it has the path to image file and it needs to set it as wallpaper. The auto wallpaper service also have to downscale the image before setting it so that it doesn't crash the system or so I have found that it crashes on large image files. In the end the resolution differs in both cases and hard to make sure they both apply the wallpaper same, that's probably why you're seeing more zoomed in wallpapers set by auto wallpaper service.

**Comment by gaabster** [comment]
Makes sense. 
Thanks for the explanation.
